### ISSUE TITLE
Perform non-valid data checks on temperature and precipitation fields

### ISSUE THREAD

**Issue by KkcChow** [ECCC-CCCS/CMIP6-BCCAQ-Quality-Control#40]
as documented [here](https://github.com/Ouranosinc/xclim/issues/65)

**Comment by KkcChow** [comment]
I ran the data_flags (i.e., ECAD) on daily precip, tasmax, and tasmin for all the model ouputs and:

- All precip simulations (all models all ssps) were flagged for very large precip events exceeding 300 mm 
- All tasmax & tasmin simulations were flagged for values outside of 5 standard deviations from climatology

I checked the target PCIC-blend and it also has the same flags.

@ssobie and @tlogan2000, is this something of major concern?

**Comment by tlogan2000** [comment]
If values are occurring in the reference data then, by design, quantile mapping techniques will typically try to reproduce them. 
I think it would be nice to determine the frequency and geographical location of the flagged values.

If flagged temperature and precip values are uniquely in the BC / Mountainous region maybe Stephen would have some insight as to whether this is expected for very mountainous terrain / the prism portion of the PCIC-blend reference.  

Quick checks indicate that :
For precipitation  (if I can believe wikipedia) there was indeed a rainfall event of ~490 mm in Ucluelet BC in the 1960s.   
For temperatures outside the +/- 5 std it's a little more complicated to get an observed record

**Comment by KkcChow** [comment]
Quickly checking precip for a few simulations - ACCESS-CM2, ssp126 has an occurrence of 990 mm in Quebec, time='2074-01-26', lat=46.125, lon=-76.20833. Some additional exceedances ranging between 300-800 mm in the same simulation between 2096-2100 seem to be concentrated in the North Western region, specifically Alaska.  

Same thing with CanESM5, ssp245 at time='2059-09-26', lat=66.125, lon=-120.20833 - an occurrence of 990 mm.

I double checked the PCIC-blend target as well - the highest precip amount is 739.35 mm, time='1995-09-17', lat=58.625, lon=137.125, also Alaska. While this is the highest value in the target, but there are a handful of other years where 300mm is exceeded.

**Comment by ssobie** [comment]
The high precip values in the mountains are not unreasonable. There are some very high precipitation amounts along the coast of BC, especially moving north into the Alaska panhandle. Many models are going to project increases in the high PCIC-Blend values.
The single grid cell spikes in Quebec and NWT look more suspect. It's possible there are some very large relative deltas from the models, but the precip amounts are likely implausible. Will have to see if there is some other issue there.

**Comment by KkcChow** [comment]
Daily precip has been patched.
